apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-proxy-nginx-conf
  namespace: prod
  creationTimestamp: "2023-02-08T06:02:32Z"
  resourceVersion: "280175494"
  uid: 1d3a3fc7-4374-4714-8fda-3fddc18bf87f
data:
  nginx.conf: |
    # For more information on configuration, see:
    #   * Official English Documentation: http://nginx.org/en/docs/
    #   * Official Russian Documentation: http://nginx.org/ru/docs/

    user nginx;
    worker_processes 2;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        upstream splunk {
            server mpnkg-splk-02;
        }

        server {
            listen       80;
            server_name  _;

            location ~ / {
                proxy_pass              https://splunk-cn:8000;
                proxy_set_header Host   'splunk-chn.jasper.com';
                proxy_set_header        X-Real-IP         $remote_addr;
                proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Host  $host;
                proxy_set_header        X-Forwarded-Port  $server_port;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_set_header        Front-End-Https   on;
            }
        }
    }