apiVersion: v1
kind: Pod                          # Pod 的 API 版本和类型
metadata:                          # Pod 的元数据
  name: nginx-pod                  # Pod 名称
  namespace: default               # Pod 所在的命名空间
  annotations:                     # Pod 的注解（可选）
    description: "This is a sample Nginx Pod"  # 描述信息
  labels:                          # 给 Pod 添加标签
    app: nginx
spec:
  restartPolicy: Always            # 重启策略
  containers:                      # Pod 中的容器列表和配置
    - name: nginx-container        # 容器名称
      image: nginx:1.21            # 容器使用的镜像
      ports:
        - containerPort: 80        # 容器内部监听的端口
      resources:                   # 资源限制（可选）
        limits:
          memory: "128Mi"          # 最大内存限制
          cpu: "500m"              # 最大 CPU 使用限制
        requests:
          memory: "64Mi"           # 最小内存请求
          cpu: "250m"              # 最小 CPU 请求

apiVersion: v1               # API 版本
kind: Pod                    # 资源类型
metadata:                    # POD 元数据
  name: busybox-time-pod     # POD 名称
  namespace: default         # POD 所在的命名空间
  labels:                    # 标签
    app: busybox-time        # 应用标签
spec:
  containers:
    - name: busybox-container # 容器名称
      image: busybox          # 容器镜像，来源于 Docker Hub
      imagePullPolicy: IfNotPresent # 镜像拉取策略
      command: ["sh", "-c", "while true; do echo $(date); sleep 5; done"] # 容器命令，持续输出当前时间

apiVersion: v1
kind: Pod
metadata:
  name: busybox-time-pod
  labels:
    app: busybox-time
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "while true; do echo $(date); sleep 5; done"]