apiVersion: apps/v1               # API版本
kind: Deployment                  # 资源类型
metadata:                         # Deployment 元数据
  name: busybox-time-deployment   # 部署名称
  labels:                         # 标签
    app: busybox-time             # 应用标签
spec:
  replicas: 1                     # 副本数
  selector:                       # 选择器，用于匹配Pod
    matchLabels:                  # 标签选择器 
      app: busybox-time           # 应用标签
  template:                       # POD 模板
    metadata:                     # POD 元数据 
      labels:                     # POD 标签
        app: busybox-time         # 应用标签
    spec:                         # POD 规范
      containers:                 # 容器列表
        - name: busybox-container # 容器名称
          image: busybox          # 容器镜像，来源于 Docker Hub
          command: ["sh", "-c", "while true; do echo $(date); sleep 5; done"] # 容器命令，持续输出当前时间

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-time-deployment
  labels:
    app: busybox-time
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-time
  template:
    metadata:
      labels:
        app: busybox-time
    spec:
      containers: 
        - name: busybox-container
          image: busybox
          command: ["sh", "-c", "while true; do echo $(date); sleep 5; done"]


apiVersion: v1                 # API版本
kind: Service                  # 资源类型
metadata:                      # Service 元数据
  name: busybox-time-service   # 服务名称
  labels:                      # 标签
    app: busybox-time          # 应用标签，用于选择器匹配对应的 Deployment
spec:                          # Service 规范
  selector:                    # 选择器，用于匹配 Pod
    app: busybox-time          # 应用标签
  ports:                       # 服务端口列表
    - protocol: TCP            # 协议类型
      port: 80                 # 服务端口
      targetPort: 80           # 目标端口，指向 Pod 中的容器端口
  type: ClusterIP              # 服务类型，ClusterIP 表示集群内部访问，外部不可访问

apiVersion: v1
kind: Service
metadata:
  name: busybox-time-service
  labels:
    app: busybox-time
spec:
  selector:
    app: busybox-time
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP           

headless-service.yaml:

apiVersion: v1
kind: Service
metadata:
  name: busybox-time-service
  labels:
    app: busybox-time
spec:
  clusterIP: None             # 标识当前 service 是 headless service
  selector:
    app: busybox-time
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#  type: ClusterIP            # 对于 headless service，不需要指定 type，注释行留着对比用

kubectl apply -f headless-service.yaml:

NAME                   TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
busybox-time-service   ClusterIP   None         <none>        80/TCP    10s